export const SET_PEDIDOS = "SET_PEDIDOS"
export const GET_USER    = 'GET_USER'
export const GET_USER_FUNC = 'GET_USER_FUNC'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_PEDIDOS_MESA = 'SET_PEDIDOS_MESA'
export const SET_PEDIDOS_MESA_TRUE = 'SET_PEDIDOS_MESA_TRUE'

export const SET_TOTALVALOR = 'SET_TOTALVALOR'
export const SET_CARDAPIO   = 'SET_CARDAPIO'
export const SET_ADICIONAR_PEDIDO_ITENS = 'SET_ADICIONAR_PEDIDO_ITENS'
export const SET_ADICIONAR_PEDIDO = 'SET_ADICIONAR_PEDIDO'
export const SET_MESAS="SET_MESAS"
export const SET_ADICIONAR_PEDIDO_MESA = 'SET_ADICIONAR_PEDIDO_MESA'

export const SET_CARDAPIO_URL = 'SET_CARDAPIO_URL'


export const SET_FECHADO_ABERTO = 'SET_FECHADO_ABERTO'
export const SET_DATA_FECHADO_ABERTO = 'SET_DATA_FECHADO_ABERTO'
export const SET_MODAL_FECHADO_ABERTO = 'SET_MODAL_FECHADO_ABERTO'

export const SET_REF_NOTA = 'SET_REF_NOTA'

export const SET_ABERTURA_VALOR = 'SET_ABERTURA_VALOR'
export const SET_CAIXAS_ANTERIORES = 'SET_CAIXAS_ANTERIORES'
export const SET_PAES           = 'SET_PAES'
//